import Hero from "components/Hero";
import Insta from "components/Insta";
import Slider from "components/Slider";
import { SliderData } from "components/SliderData";
import Head from "next/head";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Art o Graphy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        headings="Art 0 Graphy"
        message="Look through your inner eyes in every Art."
      />
      <Slider slides={SliderData} />
      <Insta />
    </>
  );
}
